package com.fcc.giphyshow.ui.details.model;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by firta on 8/13/2017.
 * The {@link io.objectbox.BoxStore} object that contains the favorite gifs
 */

@Entity
public class Favorites {
    @Id
    private long  id;
    @Index
    private String gif_id;
    private String thumbnailURL = "";
    private String mp4_url = "";
    private String gif_download_url = "";


    @Generated(173812135)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Favorites(long id, String gif_id, String thumbnailURL, String mp4_url,
            String gif_download_url) {
        this.id = id;
        this.gif_id = gif_id;
        this.thumbnailURL = thumbnailURL;
        this.mp4_url = mp4_url;
        this.gif_download_url = gif_download_url;
    }

    @Generated(1752129379)
    public Favorites() {
    }


    public String getGif_id() {
        return gif_id;
    }

    public void setGif_id(String gif_id) {
        this.gif_id = gif_id;
    }

    public String getThumbnailURL() {
        return thumbnailURL;
    }

    public void setThumbnailURL(String thumbnailURL) {
        this.thumbnailURL = thumbnailURL;
    }

    public String getMp4_url() {
        return mp4_url;
    }

    public void setMp4_url(String mp4_url) {
        this.mp4_url = mp4_url;
    }

    public String getGif_download_url() {
        return gif_download_url;
    }

    public void setGif_download_url(String gif_download_url) {
        this.gif_download_url = gif_download_url;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }


}
